site_name: vscode-ext
site_description: Create vscode extensions with Python

nav:
  - Home:
      - Overview: index.md
      - Releases:
          - Changelog: changelog.md
  - Getting Started:
      - Installation: getting-started.md
      - Creating your first extension: creating-your-extension.md
      - Creating a color theme: color-theme.md
      - Publishing your extension: publish-your-extension.md

  - Documentation:
      - Extension: documentation/extension.md
      - Command: documentation/command.md

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: deep orange
  icon:
    repo: fontawesome/brands/github
  logo: vscode-ext.png
  favicon: vscode-ext.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - admonition

repo_url: https://github.com/codewithswastik/vscode-ext

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codewithswastik/vscode-ext

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
