site_name: vscode.py
site_description: Create vscode extensions with Python
repo_url: https://github.com/codewithswastik/vscode.py
edit_uri: blob/main/docs/

nav:
  - Home:
      - Overview: index.md
      - Releases:
          - Changelog: changelog.md
  - Getting Started:
      - Installation: getting-started.md
      - Creating your first extension: creating-your-extension.md
      - Publishing your extension: publish-your-extension.md

  - Documentation:
      - Extension: documentation/extension.md
      - Command: documentation/command.md
      - Objects: documentation/objects.md
      - Window: documentation/window.md
      - Configuration: documentation/config.md

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: deep orange
  icon:
    repo: fontawesome/brands/github
  logo: vscode-ext.png
  favicon: vscode-ext.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codewithswastik/vscode.py

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
